[versions]
# libraries
kotlin = "2.3.10"
http4k = "6.27.0.0"
guava = "33.5.0-jre"
test-containers = "1.21.4"
micrometer = "1.16.2"
sollecitom-swissknife = "1.0.0-SNAPSHOT"
sollecitom-acme-schema-catalogue = "1.0.0-SNAPSHOT"
# plugins
sollecitom-gradle-plugins = "1.0.0-SNAPSHOT"
palantir-git-plugin = "4.3.0"

[libraries]
sollecitom-gradle-plugins-base = { module = "sollecitom.gradle-plugins:base", version.ref = "sollecitom-gradle-plugins" }
sollecitom-gradle-plugins-kotlin-jvm = { module = "sollecitom.gradle-plugins:kotlin-jvm", version.ref = "sollecitom-gradle-plugins" }
http4k-bom = { module = "org.http4k:http4k-bom", version.ref = "http4k" }
http4k-ops-micrometer = { module = "org.http4k:http4k-ops-micrometer" }
http4k-server-jetty = { module = "org.http4k:http4k-server-jetty" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
test-containers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "test-containers" }
acme-schema-catalogue-avro-common = { module = "sollecitom.acme-schema-catalogue:avro-common", version.ref = "sollecitom-acme-schema-catalogue" }
acme-schema-catalogue-json-common = { module = "sollecitom.acme-schema-catalogue:json-common", version.ref = "sollecitom-acme-schema-catalogue" }
swissknife-avro-schema-checker = { module = "sollecitom.swissknife:avro-schema-checker", version.ref = "sollecitom-swissknife" }
swissknife-avro-schema-catalogue-domain = { module = "sollecitom.swissknife:avro-schema-catalogue-domain", version.ref = "sollecitom-swissknife" }
swissknife-avro-schema-catalogue-test-utils = { module = "sollecitom.swissknife:avro-schema-catalogue-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-messaging-domain = { module = "sollecitom.swissknife:messaging-domain", version.ref = "sollecitom-swissknife" }
swissknife-messaging-test-utils = { module = "sollecitom.swissknife:messaging-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-ddd-domain = { module = "sollecitom.swissknife:ddd-domain", version.ref = "sollecitom-swissknife" }
swissknife-openapi-checking-checker = { module = "sollecitom.swissknife:openapi-checking-checker", version.ref = "sollecitom-swissknife" }
swissknife-openapi-checking-test-utils = { module = "sollecitom.swissknife:openapi-checking-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-cryptography-domain = { module = "sollecitom.swissknife:cryptography-domain", version.ref = "sollecitom-swissknife" }
swissknife-cryptography-implementation-bouncy-castle = { module = "sollecitom.swissknife:cryptography-implementation-bouncy-castle", version.ref = "sollecitom-swissknife" }
swissknife-protected-value-domain = { module = "sollecitom.swissknife:protected-value-domain", version.ref = "sollecitom-swissknife" }
swissknife-protected-value-factory-aes = { module = "sollecitom.swissknife:protected-value-factory-aes", version.ref = "sollecitom-swissknife" }
swissknife-pagination-domain = { module = "sollecitom.swissknife:pagination-domain", version.ref = "sollecitom-swissknife" }
swissknife-pagination-test-utils = { module = "sollecitom.swissknife:pagination-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-jwt-domain = { module = "sollecitom.swissknife:jwt-domain", version.ref = "sollecitom-swissknife" }
swissknife-jwt-test-utils = { module = "sollecitom.swissknife:jwt-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-jwt-jose4j-processor = { module = "sollecitom.swissknife:jwt-jose4j-processor", version.ref = "sollecitom-swissknife" }
swissknife-jwt-jose4j-issuer = { module = "sollecitom.swissknife:jwt-jose4j-issuer", version.ref = "sollecitom-swissknife" }
swissknife-jwt-jose4j-utils = { module = "sollecitom.swissknife:jwt-jose4j-utils", version.ref = "sollecitom-swissknife" }
swissknife-core-domain = { module = "sollecitom.swissknife:core-domain", version.ref = "sollecitom-swissknife" }
swissknife-core-utils = { module = "sollecitom.swissknife:core-utils", version.ref = "sollecitom-swissknife" }
swissknife-correlation-logging-utils = { module = "sollecitom.swissknife:correlation-logging-utils", version.ref = "sollecitom-swissknife" }
swissknife-ddd-test-utils = { module = "sollecitom.swissknife:ddd-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-test-containers-utils = { module = "sollecitom.swissknife:test-containers-utils", version.ref = "sollecitom-swissknife" }
swissknife-core-test-utils = { module = "sollecitom.swissknife:core-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-configuration-utils = { module = "sollecitom.swissknife:configuration-utils", version.ref = "sollecitom-swissknife" }
swissknife-lens-correlation-extensions = { module = "sollecitom.swissknife:lens-correlation-extensions", version.ref = "sollecitom-swissknife" }
swissknife-service-readiness-http4k = { module = "sollecitom.swissknife:service-readiness-http4k", version.ref = "sollecitom-swissknife" }
swissknife-json-utils = { module = "sollecitom.swissknife:json-utils", version.ref = "sollecitom-swissknife" }
swissknife-json-test-utils = { module = "sollecitom.swissknife:json-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-correlation-core-test-utils = { module = "sollecitom.swissknife:correlation-core-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-test-utils = { module = "sollecitom.swissknife:test-utils", version.ref = "sollecitom-swissknife" }
swissknife-compliance-checker-test-utils = { module = "sollecitom.swissknife:compliance-checker-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-avro-serialization-utils = { module = "sollecitom.swissknife:avro-serialization-utils", version.ref = "sollecitom-swissknife" }
swissknife-avro-serialization-test-utils = { module = "sollecitom.swissknife:avro-serialization-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-resource-utils = { module = "sollecitom.swissknife:resource-utils", version.ref = "sollecitom-swissknife" }
swissknife-correlation-core-domain = { module = "sollecitom.swissknife:correlation-core-domain", version.ref = "sollecitom-swissknife" }
swissknife-web-api-domain = { module = "sollecitom.swissknife:web-api-domain", version.ref = "sollecitom-swissknife" }
swissknife-web-api-utils = { module = "sollecitom.swissknife:web-api-utils", version.ref = "sollecitom-swissknife" }
swissknife-web-api-test-utils = { module = "sollecitom.swissknife:web-api-test-utils", version.ref = "sollecitom-swissknife" }
swissknife-logger-core = { module = "sollecitom.swissknife:logger-core", version.ref = "sollecitom-swissknife" }
swissknife-pulsar-utils = { module = "sollecitom.swissknife:pulsar-utils", version.ref = "sollecitom-swissknife" }
swissknife-http4k-server-utils = { module = "sollecitom.swissknife:http4k-server-utils", version.ref = "sollecitom-swissknife" }
swissknife-pulsar-avro-utils = { module = "sollecitom.swissknife:pulsar-avro-utils", version.ref = "sollecitom-swissknife" }
swissknife-pulsar-json-utils = { module = "sollecitom.swissknife:pulsar-json-utils", version.ref = "sollecitom-swissknife" }
swissknife-pulsar-json-serialization = { module = "sollecitom.swissknife:pulsar-json-serialization", version.ref = "sollecitom-swissknife" }
swissknife-pulsar-messaging-adapter = { module = "sollecitom.swissknife:pulsar-messaging-adapter", version.ref = "sollecitom-swissknife" }
swissknife-logging-standard-slf4j-configuration = { module = "sollecitom.swissknife:logging-standard-slf4j-configuration", version.ref = "sollecitom-swissknife" }
swissknife-kotlin-extensions = { module = "sollecitom.swissknife:kotlin-extensions", version.ref = "sollecitom-swissknife" }
swissknife-web-client-info-analyzer = { module = "sollecitom.swissknife:web-client-info-analyzer", version.ref = "sollecitom-swissknife" }

[plugins]
com-palantir-git-version = { id = "com.palantir.git-version", version.ref = "palantir-git-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
